test(initial): FE-00 Adds initial commit of tests
- Installs Playwright as a testing library
- Adds initial tests for `classNames` function, and `TextInput` component
- Adds pre-commit hook to run tests and prevent commits that cause test to fail

Additionally, adds some initial content to the `README`.

TODO: Add some kind of script to show/output

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -8,32 +8,60 @@ fi
 # Make sure we're navigated to the top level of the git tree
 cd "$(git rev-parse --show-toplevel)"
 
-# Set the location of the ESLint binary
-NEXTJS="./node_modules/.bin/next"
+# Set the location of the ESLint, TypeScript, and Playwright binaries
+ESLINT="./node_modules/.bin/eslint"
 TSC="./node_modules/.bin/tsc"
+PLAYWRIGHT="./node_modules/.bin/playwright"
 CUR_DIR=pwd
 pwd
 
 # If ESLint is not installed display an error and exit, preventing commit.
-if [[ ! -x "$NEXTJS" ]]; then
-    printf "NextJS does not seem to be installed\n"
+if [[ ! -x "$ESLINT" ]]; then
+    printf "ESLint does not seem to be installed\n"
     exit 1
 fi
 
-# If ESLint is not installed display an error and exit, preventing commit.
-if [[ ! -x "$NEXTJS" ]]; then
+# If TypeScript is not installed display an error and exit, preventing commit.
+if [[ ! -x "$TSC" ]]; then
     printf "TypeScript does not seem to be installed\n"
     exit 1
 fi
 
+# If TypeScript is not installed display an error and exit, preventing commit.
+if [[ ! -x "$PLAYWRIGHT" ]]; then
+    printf "Playwright does not seem to be installed\n"
+    exit 1
+fi
+
 # Perform Linting
-npm run pre-commit
+npm run lint
 EXIT_CODE="$?"
 
 # If ESlint exited without error, commit can go ahead. Otherwise, stop.
 if [[ "${EXIT_CODE}" != 0 ]]; then
-    printf "\nPRE-COMMIT CHECKS FAILED: Please fix errors and try again.\n"
+    printf "\nPRE-COMMIT LINTING FAILED: Please fix errors and try again.\n"
     exit 1
 fi
+
+# Perform Type Checks
+npm run type-check
+EXIT_CODE="$?"
+
+# If ESlint exited without error, commit can go ahead. Otherwise, stop.
+if [[ "${EXIT_CODE}" != 0 ]]; then
+    printf "\nPRE-COMMIT TYPE CHECKS FAILED: Please fix errors and try again.\n"
+    exit 1
+fi
+
+# Run Tests
+npm run test
+EXIT_CODE="$?"
+
+# If ESlint exited without error, commit can go ahead. Otherwise, stop.
+if [[ "${EXIT_CODE}" != 0 ]]; then
+    printf "\nPRE-COMMIT TESTS FAILED: Please fix errors and try again.\n"
+    exit 1
+fi
+
 
 exit $?
